package de.steenken.combatrunner.control;

public enum UserAction {
	NEW_COMBAT,
	LOAD_COMBAT,
	SAVE_COMBAT,
	NEW_COMBATANT,
	LOAD_COMBATANT,
	SAVE_COMBATANT,
	ADD_COMBATANT,
	REMOVE_COMBATANT,
	START_COMBAT,
	RESET_COMBAT,
	COMBATANT_ACTS,
	COMBATANT_RECEIVES_DAMAGE,
	COMBATANT_RECEIVES_MODIFIER,
	COMBATANT_LOOSES_MODIFIER,
	COMBATANT_ROLLS_INITIATIVE,
	QUIT
}
